### ISSUE TITLE
Mobile view (max-width: 700px) responsiveness done.

### ISSUE THREAD

**Issue by vedamruta** [Badbatunde/portfolio#2]
Hello. I have made the mobile view of website responsive. The breakpoint that you took (max-width: 700px), so I have modified code for the same breakpoint. Also, I haven't removed the red borders that you applied for debugging as their presence would be helpful. I have attached the screenshots of the same below. 
Thank you :) their
![img0](https://user-images.githubusercontent.com/96135994/230429024-f2aa2e55-9d5d-4861-a776-ddf74fdb5aa8.PNG)
![img1](https://user-images.githubusercontent.com/96135994/230429125-88076291-ca05-4e60-831d-a4098c2f5758.PNG)
![img2](https://user-images.githubusercontent.com/96135994/230429364-106e24d4-c066-4167-9922-cb53f40e6e00.PNG)
![img3](https://user-images.githubusercontent.com/96135994/230429514-1af9ef46-149e-412a-a32c-172c94ccdcf6.PNG)
![img4](https://user-images.githubusercontent.com/96135994/230429613-ca469391-34f7-45d6-8a85-e1ce41e5d4eb.PNG)
![img5](https://user-images.githubusercontent.com/96135994/230429711-e3d7b521-9fdc-4bdc-a103-169b4ba33317.PNG)
![img6](https://user-images.githubusercontent.com/96135994/230429879-82b2d46d-f827-4606-a397-00d0a3077995.PNG)
![img7](https://user-images.githubusercontent.com/96135994/230430038-6751fd03-cee4-4c00-9bb1-efa482c03334.PNG)

**Comment by Badbatunde** [comment]
Getting better.
